import type { Nutrient } from "./types";

const reviewedAt = "2026-08-20";

export const nutrients: Nutrient[] = [
  {
    slug: "vitamin-a",
    name: "Vitamin A",
    category: "vitamin",
    bodyFunctions: ["vision", "immune function", "growth"],
    summary: "Supports vision, immune function, and healthy growth.",
    whatItDoes: "Vitamin A supports vision, immune function, and the health of skin and tissues.",
    foodSources: "Liver, eggs, dairy foods, and orange or dark-green vegetables provide vitamin A or its precursors.",
    globalLens: "Deficiency risk is shaped by dietary diversity, infection, food access, and maternal and child health services.",
    safetyNote: "High-dose vitamin A can be harmful. Food and supplement decisions should be discussed with a qualified professional.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/VitaminA-Consumer/",
    reviewedAt,
  },
  {
    slug: "vitamin-d",
    name: "Vitamin D",
    category: "vitamin",
    bodyFunctions: ["bone health", "muscle function", "immune function"],
    summary: "Helps the body use calcium and supports bones and muscles.",
    whatItDoes: "Vitamin D helps the body absorb calcium and supports bone, muscle, nerve, and immune function.",
    foodSources: "Fatty fish, egg yolks, fortified foods, and sunlight exposure can contribute to vitamin D status.",
    globalLens: "Latitude, housing, outdoor work, skin pigmentation, pollution, and food fortification influence population patterns.",
    safetyNote: "Too much vitamin D from supplements can cause harm. Needs vary with age, health, and other factors.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/VitaminD-Consumer/",
    reviewedAt,
  },
  {
    slug: "vitamin-b12",
    name: "Vitamin B12",
    category: "vitamin",
    bodyFunctions: ["blood cells", "nerve function", "DNA"],
    summary: "Supports blood cells, nerves, and DNA production.",
    whatItDoes: "Vitamin B12 helps keep blood and nerve cells healthy and helps make DNA.",
    foodSources: "Fish, meat, poultry, eggs, dairy foods, and fortified foods are common sources.",
    globalLens: "Dietary patterns, affordability, cultural foodways, food fortification, and access to testing shape risk.",
    safetyNote: "Low status can have different causes. Persistent symptoms need qualified medical advice rather than self-diagnosis.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/VitaminB12-Consumer/",
    reviewedAt,
  },
  {
    slug: "folate",
    name: "Folate",
    category: "vitamin",
    bodyFunctions: ["cell division", "DNA", "red blood cells"],
    summary: "Helps cells divide and supports DNA and red blood cell formation.",
    whatItDoes: "Folate is needed to make DNA and other genetic material and for cells to divide.",
    foodSources: "Leafy greens, beans, citrus, and fortified grain products contribute folate.",
    globalLens: "Fortification policy, prenatal care access, food affordability, and dietary diversity can change outcomes at scale.",
    safetyNote: "Pregnancy-related needs are individualized. High supplemental folic acid can mask some signs of vitamin B12 deficiency.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/Folate-Consumer/",
    reviewedAt,
  },
  {
    slug: "iron",
    name: "Iron",
    category: "mineral",
    bodyFunctions: ["hemoglobin", "oxygen transport", "energy metabolism"],
    summary: "Helps make hemoglobin and transport oxygen through the body.",
    whatItDoes: "Iron supports hemoglobin and oxygen transport, as well as energy metabolism and cellular function.",
    foodSources: "Meat, seafood, beans, lentils, tofu, leafy greens, and fortified grains can provide iron.",
    globalLens: "Food access, infections, socioeconomic conditions, blood loss, and healthcare access influence outcomes.",
    safetyNote: "Iron supplements can be dangerous when unnecessary or taken in excess. Deficiency should not be diagnosed from a website.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/Iron-Consumer/",
    reviewedAt,
  },
  {
    slug: "iodine",
    name: "Iodine",
    category: "mineral",
    bodyFunctions: ["thyroid hormones", "metabolism", "growth"],
    summary: "Enables thyroid hormone production and supports growth and metabolism.",
    whatItDoes: "Iodine is needed to make thyroid hormones, which guide metabolism and development.",
    foodSources: "Iodized salt, seafood, dairy foods, and eggs can contribute iodine depending on local food systems.",
    globalLens: "Universal salt iodization shows how a coordinated policy can reach populations through a widely used food vehicle.",
    safetyNote: "Both too little and too much iodine can affect health. Local guidance matters because food systems differ.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/Iodine-Consumer/",
    reviewedAt,
  },
  {
    slug: "zinc",
    name: "Zinc",
    category: "mineral",
    bodyFunctions: ["immune function", "wound healing", "growth"],
    summary: "Supports immune function, wound healing, and normal growth.",
    whatItDoes: "Zinc supports the immune system, helps wounds heal, and is important for growth and development.",
    foodSources: "Meat, shellfish, dairy foods, beans, nuts, and whole grains provide zinc in different amounts.",
    globalLens: "Dietary patterns, food processing, infection burden, and access to maternal and child services shape risk.",
    safetyNote: "Long-term high-dose zinc can interfere with copper absorption and other functions.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/Zinc-Consumer/",
    reviewedAt,
  },
  {
    slug: "magnesium",
    name: "Magnesium",
    category: "mineral",
    bodyFunctions: ["muscle and nerve function", "blood glucose", "bone health"],
    summary: "Supports muscles, nerves, blood glucose regulation, and bones.",
    whatItDoes: "Magnesium participates in hundreds of biochemical reactions, including muscle, nerve, and bone functions.",
    foodSources: "Nuts, seeds, beans, whole grains, and leafy green vegetables are useful food sources.",
    globalLens: "Food affordability, processing patterns, agricultural diversity, and access to varied diets influence intake.",
    safetyNote: "Supplemental magnesium can interact with medicines and cause side effects. Needs vary across people.",
    source: "NIH Office of Dietary Supplements",
    sourceUrl: "https://ods.od.nih.gov/factsheets/Magnesium-Consumer/",
    reviewedAt,
  },
];
